package GUI;

import Controlador.LogicaNegocio;
import DTOs.Contacto;
import TableModels.TablaContactos;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author aranx
 */
public class VentanaCrearContacto extends javax.swing.JDialog {

    private VentanaPrincipal parent;

    /**
     * Creates new form VentanaCrearContacto
     */
    public VentanaCrearContacto(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.parent = (VentanaPrincipal) parent;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jL_nombre = new javax.swing.JLabel();
        jL_apellidos = new javax.swing.JLabel();
        jL_dni = new javax.swing.JLabel();
        jTF_nombre = new javax.swing.JTextField();
        jTF_apellidos = new javax.swing.JTextField();
        jTF_dni = new javax.swing.JTextField();
        jB_aceptar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jL_nombre.setText("Nombre: ");

        jL_apellidos.setText("Apellidos: ");

        jL_dni.setText("DNI: ");

        jB_aceptar.setText("ACEPTAR");
        jB_aceptar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jB_aceptarMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jB_aceptar)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jL_apellidos)
                            .addComponent(jL_nombre)
                            .addComponent(jL_dni))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTF_dni, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTF_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTF_apellidos, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(74, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jL_nombre)
                    .addComponent(jTF_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(54, 54, 54)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jL_apellidos)
                    .addComponent(jTF_apellidos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(47, 47, 47)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jL_dni)
                    .addComponent(jTF_dni, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(41, 41, 41)
                .addComponent(jB_aceptar)
                .addContainerGap(59, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jB_aceptarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jB_aceptarMouseClicked
        // Creamos un Contacto con los textos contenidos en cada uno de los textField
        Contacto contacto = new Contacto(jTF_nombre.getText(), jTF_apellidos.getText(), jTF_dni.getText());
        // Añadimos el Contacto a la lista del TableModel (que será la misma que del controlador)
        TablaContactos tablaContactos=(TablaContactos) parent.getjT_tabla().getModel();
        tablaContactos.addRow(contacto);
        // Refrescamos el objeto TableModel de la JTable que contiene los datos
        parent.refrescarTabla();
        // Cerramos esta ventana para volver de nuevo a la principal
        dispose();
    }//GEN-LAST:event_jB_aceptarMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jB_aceptar;
    private javax.swing.JLabel jL_apellidos;
    private javax.swing.JLabel jL_dni;
    private javax.swing.JLabel jL_nombre;
    private javax.swing.JTextField jTF_apellidos;
    private javax.swing.JTextField jTF_dni;
    private javax.swing.JTextField jTF_nombre;
    // End of variables declaration//GEN-END:variables
}
