/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package textFieldPersonalizado;

import java.awt.Color;

/**
 *
 * @author aranx
 */
public class PropiedadesTextFieldPanel extends javax.swing.JPanel {

    /**
     * Creates new form PropiedadesTextFieldPanel
     */
    public PropiedadesTextFieldPanel() {
        initComponents();
    }

    public PropiedadesTextField getPropiedadesTextField() {
        return new PropiedadesTextField(jComboBox_tipoDato.getSelectedIndex(),
                                        new Color(Integer.valueOf(jTF_colorNormal.getText())),
                                        new Color(Integer.valueOf(jTF_colorAlerta.getText())));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jB_colorNormal = new javax.swing.JButton();
        jTF_colorNormal = new javax.swing.JTextField();
        jB_colorAlerta = new javax.swing.JButton();
        jTF_colorAlerta = new javax.swing.JTextField();
        jColorChooser = new javax.swing.JColorChooser();
        jLabel1 = new javax.swing.JLabel();
        jComboBox_tipoDato = new javax.swing.JComboBox<>();

        jB_colorNormal.setText("Color por defecto");
        jB_colorNormal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_colorNormalActionPerformed(evt);
            }
        });

        jTF_colorNormal.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jTF_colorNormal.setText("000000");

        jB_colorAlerta.setText("Color de alerta");
        jB_colorAlerta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_colorAlertaActionPerformed(evt);
            }
        });

        jTF_colorAlerta.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jTF_colorAlerta.setText("000000");

        jColorChooser.setColor(new java.awt.Color(0, 0, 0));

        jLabel1.setText("Tipo de dato:");

        jComboBox_tipoDato.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "DNI", "Teléfono", "E-mail", "Numérico", "Alfabético", "Alfanumérico" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jB_colorNormal)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTF_colorNormal, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(21, 21, 21)
                        .addComponent(jB_colorAlerta)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTF_colorAlerta, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jComboBox_tipoDato, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jColorChooser, javax.swing.GroupLayout.PREFERRED_SIZE, 698, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(31, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTF_colorNormal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jTF_colorAlerta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jB_colorAlerta)
                        .addComponent(jLabel1)
                        .addComponent(jComboBox_tipoDato, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jB_colorNormal, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(18, 18, 18)
                .addComponent(jColorChooser, javax.swing.GroupLayout.PREFERRED_SIZE, 378, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(191, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jB_colorNormalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_colorNormalActionPerformed
        // Ponemos el color de letra y el valor RGB seleccionados en el jColorChooser al jTextField
        jTF_colorNormal.setForeground(jColorChooser.getColor());
        jTF_colorNormal.setText(String.valueOf(jColorChooser.getColor().getRGB()));
    }//GEN-LAST:event_jB_colorNormalActionPerformed

    private void jB_colorAlertaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_colorAlertaActionPerformed
        // Ponemos el color de letra y el valor RGB seleccionados en el jColorChooser al jTextField
        jTF_colorAlerta.setForeground(jColorChooser.getColor());
        jTF_colorAlerta.setText(String.valueOf(jColorChooser.getColor().getRGB()));
    }//GEN-LAST:event_jB_colorAlertaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jB_colorAlerta;
    private javax.swing.JButton jB_colorNormal;
    private javax.swing.JColorChooser jColorChooser;
    private javax.swing.JComboBox<String> jComboBox_tipoDato;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField jTF_colorAlerta;
    private javax.swing.JTextField jTF_colorNormal;
    // End of variables declaration//GEN-END:variables
}
