
package GUI;

import DTO.OperacionBancaria;
import Modelo.TableOperacionBancaria;
import java.awt.Color;
import java.util.Date;
import java.util.GregorianCalendar;

/**
 *
 * @author aranx
 */
public class VentanaSecundaria extends javax.swing.JDialog {

    private PantallaPrincipal parent;

    /**
     * Creates new form VentanaSecundaria
     */
    public VentanaSecundaria(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.parent = (PantallaPrincipal) parent;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel_importe = new javax.swing.JLabel();
        jLabel_concepto = new javax.swing.JLabel();
        jLabel_fecha = new javax.swing.JLabel();
        jTextField_importe = new javax.swing.JTextField();
        jTextField_concepto = new javax.swing.JTextField();
        jSpinner_fecha = new javax.swing.JSpinner();
        jButton_ok = new javax.swing.JButton();
        jButton_cancel = new javax.swing.JButton();
        jLabel_avisoImporte = new javax.swing.JLabel();
        jLabel_avisoConcepto = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        jLabel_importe.setText("Importe:");

        jLabel_concepto.setText("Concepto:");

        jLabel_fecha.setText("Fecha:");

        jTextField_importe.setToolTipText("");

        jSpinner_fecha.setModel(new javax.swing.SpinnerDateModel(new java.util.Date(), new java.util.Date(), null, java.util.Calendar.DAY_OF_MONTH));

        jButton_ok.setText("OK");
        jButton_ok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_okActionPerformed(evt);
            }
        });

        jButton_cancel.setText("CANCEL");
        jButton_cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_cancelActionPerformed(evt);
            }
        });

        jLabel_avisoImporte.setForeground(new java.awt.Color(255, 0, 153));

        jLabel_avisoConcepto.setForeground(new java.awt.Color(255, 0, 153));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel_fecha, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_importe)
                    .addComponent(jLabel_concepto))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jTextField_concepto, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jSpinner_fecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField_importe, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel_avisoImporte, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel_avisoConcepto, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton_cancel)
                        .addGap(51, 51, 51)
                        .addComponent(jButton_ok)))
                .addContainerGap(24, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(55, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel_importe)
                        .addComponent(jTextField_importe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel_avisoImporte, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel_fecha)
                            .addComponent(jSpinner_fecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(98, 98, 98))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel_avisoConcepto, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jTextField_concepto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel_concepto)))
                        .addGap(72, 72, 72)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton_ok)
                            .addComponent(jButton_cancel))
                        .addContainerGap(32, Short.MAX_VALUE))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_cancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_cancelActionPerformed
        dispose();
    }//GEN-LAST:event_jButton_cancelActionPerformed
   
    private void jButton_okActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_okActionPerformed
        // Borramos los avisos de los campos que ya estén rellenados
        if (jTextField_importe.getText() != null && !jTextField_importe.getText().equals("")) {
            jLabel_avisoImporte.setText("");
        }
        if (jTextField_concepto!=null&&!jTextField_concepto.getText().equals("")) {
            jLabel_avisoConcepto.setText("");
        }
        // Declaramos dos variables para comprobar que los jTextFields no estén vacíos
        boolean correctoImporte = true;
        boolean correctoConcepto = true;
        if (jTextField_importe.getText() == null||jTextField_importe.getText().equals("")) {
            jLabel_avisoImporte.setText("Obligatorio");
            correctoImporte = false;
        }
        if (jTextField_concepto.getText() == null||jTextField_concepto.getText().equals("")) {
            jLabel_avisoConcepto.setText("Obligatorio");
            correctoConcepto = false;
        }
        if (correctoImporte==true && correctoConcepto==true) {
            GregorianCalendar fecha = new GregorianCalendar();
            fecha.setTime((Date) jSpinner_fecha.getValue());
            float importe = Float.valueOf(jTextField_importe.getText());
            OperacionBancaria operacion = new OperacionBancaria(importe, jTextField_concepto.getText(), fecha);
            TableOperacionBancaria model = (TableOperacionBancaria) parent.getjTable_tabla().getModel();
            model.addOperacion(operacion);
            parent.refrescarTabla();
            dispose();
        }
    }//GEN-LAST:event_jButton_okActionPerformed

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_cancel;
    private javax.swing.JButton jButton_ok;
    private javax.swing.JLabel jLabel_avisoConcepto;
    private javax.swing.JLabel jLabel_avisoImporte;
    private javax.swing.JLabel jLabel_concepto;
    private javax.swing.JLabel jLabel_fecha;
    private javax.swing.JLabel jLabel_importe;
    private javax.swing.JSpinner jSpinner_fecha;
    private javax.swing.JTextField jTextField_concepto;
    private javax.swing.JTextField jTextField_importe;
    // End of variables declaration//GEN-END:variables
}
